log4perl.category = WARN, LOG
log4perl.appender.LOG = Log::Log4perl::Appender::File
log4perl.appender.LOG.filename = log/sort-images.log
log4perl.appender.LOG.mode = append
log4perl.appender.LOG.layout = Log::Log4perl::Layout::PatternLayout
log4perl.appender.LOG.layout.ConversionPattern =%d [%p] %m%n
